COMP: Add missing module dependency on ITKIOImageBase
Fixing compile error which occurs during wrapping:

C:/Dev/ITK-vs22/Wrapping/castxml_inputs/itkScancoImageIO.cxx:1:10: fatal error: 'itkCommand.h' file not found